# Target Drive
DRIVE="/dev/nvme0n1"

# Networking & Localization
HOSTNAME="arch-dell"
USERNAME="jdoe"         
FULLNAME="John Doe"    
TIMEZONE="America/Chicago"
LOCALE="en_US.UTF-8"

# Btrfs Subvolumes
SUBVOLS=("@:/" "@home:/home" "@var_log:/var/log" "@snapshots:/.snapshots")

# Packages
PKGS=(
    "base" "base-devel" "linux" "linux-firmware" "amd-ucode" "btrfs-progs"
    "grub" "efibootmgr" "zram-generator" "dosfstools" "coreutils" "util-linux"
    "pciutils" "usbutils" "bind" "sd" "htop" "btop" "nvme-cli" "smartmontools"
    "lsof" "strace" "iproute2" "iputils" "nmap" "tcpdump" "mtr" "iperf3" 
    "ethtool" "net-tools" "wget" "curl" "rsync" "openssh" "snapper" "snap-pac" 
    "grub-btrfs" "pacman-contrib" "zsh" "zsh-completions" "zsh-autosuggestions" 
    "zsh-syntax-highlighting" "vi" "nano" "fastfetch" "git" "xdg-user-dirs" 
    "iw" "iwd" "network-manager-applet" "terminus-font"
)
