# Target Drive
DRIVE="/dev/nvme0n1"

# Networking & Localization
HOSTNAME="arch-dell"
USERNAME="jdoe"         
FULLNAME="John Doe"    
TIMEZONE="America/Chicago"
LOCALE="en_US.UTF-8"

# Btrfs Subvolumes
SUBVOLS=(
    "@:/"
    "@home:/home"
    "@var_log:/var/log"
    "@snapshots:/.snapshots"
)

# Packages
PKGS=(
    "base" "base-devel" "linux" "linux-firmware" "amd-ucode"
    "btrfs-progs" "networkmanager" "grub" "efibootmgr"
    "vi" "nano" "sudo" "man-db" "man-pages" "texinfo" "dosfstools"
    "zram-generator" "git" "pacman-contrib"
)
